### ISSUE TITLE
Openbare geheime informatie

### ISSUE THREAD

**Issue by Periodic1911** [mrkoendb/EPO_2_Vroom_Vroom#1]
Leuk om je code in te zien, maar je hoort het niet openbaar te maken.
Als volgend jaar een sjaars dit kopieert ben je medeplichtig aan plagiaat.

**Comment by mrkoendb** [comment]
Ik ben vergeten dat ik inmiddels niet meer betaal voor Github, hiervoor was dit een privé project op Github. Ik zal dit oplossen zodra ik terug ben van vakantie door een local backup te maken en daarna alles van Github te gooien.
